---
version: "3.8"
services:
  dispatch:
    image: khlieng/dispatch:latest
    container_name: ${HOST_NAME}.${DOMAIN_NAME}
    restart: unless-stopped
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - data:/data
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    deploy:
      labels:
        - "traefik.enable=true"
        #- "traefik.http.middlewares.${HOST_NAME}.basicauth.users=${USER_DATA}"
        - "traefik.http.routers.${HOST_NAME}.rule=Host(`${HOST_NAME}.${DOMAIN_NAME}`)"
        - "traefik.http.routers.${HOST_NAME}.entrypoints=websecure"        
        - "traefik.http.services.${HOST_NAME}.loadbalancer.server.port=80"
    configs:
      - source: dispatch_config
        target: config.toml

configs:
  dispatch_config:
     external: true
    
networks:
  traefik:
    external: true

volumes:
    data:
