---
version: "3"
services:
  dispatch:
    image: khlieng/dispatch:latest
    container_name: ${HOST_NAME}.${DOMAIN_NAME}
    restart: unless-stopped
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - data:/data
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.%{HOST_NAME}.basicauth.users=%{USER_DATA}"
        - "traefik.http.routers.u${HOST_NAME}.rule=Host(`${HOST_NAME}.${DOMAIN_NAME}`)"
        - "traefik.http.services.u${HOST_NAME}.loadbalancer.server.port=443"
        - "traefik.http.routers.u${HOST_NAME}.entrypoints=websecure"
        - "traefik.http.services.u${HOST_NAME}loadbalancer.server.scheme=https"
      # - "traefik.http.routers.${HOST_NAME}.tls.certresolver=le"

networks:
  traefik:
    external: true

volumes:
    data:
