---
version: "3"
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: ${HOST_NAME}.${DOMAIN_NAME}
    restart: unless-stopped
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - filebrowser_root:/srv 
       - filebrowser.db:/database.db 
       - filebrowser.json:/.filebrowser.json
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.u${HOST_NAME}.rule=Host(`${HOST_NAME}.${DOMAIN_NAME}`)"
      - "traefik.http.services.u${HOST_NAME}.loadbalancer.server.port=80"
      - "traefik.http.routers.u${HOST_NAME}.entrypoints=websecure"
      - "traefik.http.routers.u${HOST_NAME}.tls.certresolver=le"

networks:
  traefik:
    external: true

volumes:
    srv:
    filebrowser.db:
    filebrowser.json:
    
