---
version: "3"
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: ${HOST_NAME}.${DOMAIN_NAME}
    restart: unless-stopped
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - filebrowser_srv:/srv
       - filebrowser_data:/data
    command: "--port 80 --database /data/database.db --root /srv"
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.u${HOST_NAME}.rule=Host(`${HOST_NAME}.${DOMAIN_NAME}`)"
        - "traefik.http.services.u${HOST_NAME}.loadbalancer.server.port=80"
        - "traefik.http.routers.u${HOST_NAME}.entrypoints=websecure"
       # - "traefik.http.routers.u${HOST_NAME}.tls.certresolver=le"

networks:
  traefik:
    external: true

volumes:
    filebrowser_srv:
    filebrowser_data:
    

    
