---
version: "3"
services:
  gitea:
    image: gitea/gitea:latest
    container_name: ${HOST_NAME}.${DOMAIN_NAME}-app
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    depends_on:
      - db
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - app_data:/data
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${HOST_NAME}.rule=Host(`${HOST_NAME}.${DOMAIN_NAME}`)"
      - "traefik.http.services.${HOST_NAME}.loadbalancer.server.port=3000"
      - "traefik.http.routers.${HOST_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${HOST_NAME}.tls.certresolver=le"
      - "traefik.docker.network=traefik" 
      
  db:
     image: mysql:8
     restart: always
     container_name: ${HOST_NAME}.${DOMAIN_NAME}-db
     environment:
       - MYSQL_ROOT_PASSWORD=gitea
       - MYSQL_USER=gitea
       - MYSQL_PASSWORD=gitea
       - MYSQL_DATABASE=gitea
     networks:
      - db
     volumes:
      - db_data:/var/lib/mysql

networks:
  traefik:
    external: true
  db:

volumes:
    app_data:
    db_data:
