---
version: "2.1"
services:
  portainer:
    image: gitea/gitea:latest
    container_name: ${HOSTNAME}-${DOMAINNAME}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.u${HOSTNAME}.rule=Host(`${HOSTNAME}.${DOMAINNAME}`)"
      - "traefik.http.services.u${HOSTNAME}.loadbalancer.server.port=3000"
      - "traefik.http.routers.u${HOSTNAME}.entrypoints=websecure"
      - "traefik.http.routers.u${HOSTNAME}.tls.certresolver=le"

networks:
  traefik:
    external: true
