   
---
version: "3"
services:
  minio:
    image: minio/minio:latest
    container_name: ${HOST_NAME}.${DOMAIN_NAME}
    restart: unless-stopped
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - data:/data
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    environment:
      - "MINIO_ROOT_USER=${ROOT_NAME}"
      - "MINIO_ROOT_PASSWORD=${ROOT_SECRET}"
    command: 
      - "server" 
      - "/data" 
      - "--console-address"
      - ":${PORT}"
      - "--address"
      - ":${APIPORT}"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${HOST_NAME}-console.rule=Host(`${HOST_NAME}-console.${DOMAIN_NAME}`)"
        - "traefik.http.services.${HOST_NAME}-console.loadbalancer.server.port=${PORT}"
        - "traefik.http.routers.${HOST_NAME}-console.entrypoints=websecure"
        - "traefik.http.routers.${HOST_NAME}.rule=Host(`${HOST_NAME}.${DOMAIN_NAME}`)"
        - "traefik.http.services.${HOST_NAME}.loadbalancer.server.port=${APIPORT}"
        - "traefik.http.routers.${HOST_NAME}.entrypoints=websecure"


networks:
  traefik:
    external: true

volumes:
    data:
