version: '3'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.4
    container_name: db-${HOST_NAME}.${DOMAIN_NAME}
    restart: always
    networks:
      - db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW 
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    container_name: ${HOST_NAME}.${DOMAIN_NAME}
    restart: always
    links:
      - db
    networks:
      - traefik
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.u${HOST_NAME}.rule=Host(`${HOST_NAME}.${DOMAIN_NAME}`)"
      - "traefik.http.services.u${HOST_NAME}.loadbalancer.server.port=80"
      - "traefik.http.routers.u${HOST_NAME}.entrypoints=websecure"
      - "traefik.http.routers.u${HOST_NAME}.tls.certresolver=le"
      - "traefik.docker.network=traefik" 
      
networks:
  traefik:
    external: true
  db:
