version: '3'

services:
  mysql:
    image: mysql:5.8
    networks:  
      - ipam-sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT}
    restart: always
    volumes:
      - db_data:/var/lib/mysql
  ipam:
    depends_on:
      - mysql
    image: pierrecdn/phpipam
    networks:
      - traefik
      - ipam-sql
    environment:
      - MYSQL_ENV_MYSQL_USER=root
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=${MYSQL_ROOT}
      - MYSQL_ENV_MYSQL_HOST=mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.u${HOST_NAME}.rule=Host(`${HOST_NAME}.${DOMAIN_NAME}`)"
      - "traefik.http.services.u${HOST_NAME}.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.u${HOST_NAME}.entrypoints=websecure"
      - "traefik.http.routers.u${HOST_NAME}.tls.certresolver=le"

networks:
  traefik:
    external: true
  ipam-sql:

volumes:
  db_data:
 
